#!/bin/bash
#SBATCH --job-name=tune
#SBATCH --output=out_tune.log
#SBATCH --error=error_tune.log

#SBATCH --partition=gpu
#SBATCH --qos=gpu
#SBATCH --gres=gpu

#SBATCH --cpus-per-task=2
#SBATCH --mem=64G

source /pyvenv/bin/activate

python3 parallel_hyperband_tuning_worker.py --out_path=${OUT_PATH} --experiment_id=${EXPERIMENT_ID} --max_epochs=${MAX_EPOCHS} --factor=${FACTOR} --bracket=${BRACKET} --in_path=${IN_PATH}  > ${OUT_PATH}/tuning_info_${EXPERIMENT_ID}_${MAX_EPOCHS}_${FACTOR}_${BRACKET}.txt

deactivate
